/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApiKey = string;
export type ApiKeyHash = string;
export type Day = bigint;
export interface Membership {
  'role' : Role,
  'user' : Principal,
  'tenantId' : TenantId,
}
export interface RateLimitStatus {
  'resetTimestamp' : Time,
  'used' : bigint,
  'limit' : bigint,
}
export type Role = { 'Viewer' : null } |
  { 'Member' : null } |
  { 'Admin' : null };
export interface Tenant {
  'id' : TenantId,
  'apiKeyHash' : ApiKeyHash,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
}
export type TenantId = string;
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface WebhookConfig {
  'url' : [] | [string],
  'signingSecret' : string,
  'enabled' : boolean,
  'enabledEvents' : Array<string>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addMemberByPrincipal' : ActorMethod<[Principal, Role], undefined>,
  'authenticateWithAPIKey' : ActorMethod<[ApiKey], Tenant>,
  'configureWebhook' : ActorMethod<[string, Array<string>], string>,
  'getAnalyticsSummary' : ActorMethod<
    [TenantId, bigint],
    {
      'webhookHealth' : { 'failure' : bigint, 'success' : bigint },
      'activeEndUsers' : bigint,
      'totalApiCalls' : bigint,
      'authSuccessRate' : bigint,
    }
  >,
  'getCurrentTenant' : ActorMethod<[], Tenant>,
  'getDailyTrend' : ActorMethod<[TenantId, bigint], Array<[Day, bigint]>>,
  'getEventBreakdown' : ActorMethod<
    [TenantId],
    { 'authenticated' : bigint, 'failed' : bigint, 'registered' : bigint }
  >,
  'getOrCreateTenant' : ActorMethod<[], Tenant>,
  'getRateLimitStatus' : ActorMethod<[ApiKeyHash], RateLimitStatus>,
  'getTenantMembers' : ActorMethod<[], Array<Membership>>,
  'getUserRole' : ActorMethod<[], Role>,
  'getWebhookConfig' : ActorMethod<
    [],
    {
      'url' : [] | [string],
      'enabled' : boolean,
      'enabledEvents' : Array<string>,
    }
  >,
  'getWebhookDeliveries' : ActorMethod<[], Array<WebhookConfig>>,
  'recordAuthEvent' : ActorMethod<
    [TenantId, string, string, boolean],
    undefined
  >,
  'recordWebhookEvent' : ActorMethod<[TenantId, boolean], undefined>,
  'regenerateApiKey' : ActorMethod<[], ApiKey>,
  'removeMember' : ActorMethod<[Principal], undefined>,
  'testWebhook' : ActorMethod<[], { 'status' : number, 'message' : string }>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateMemberRole' : ActorMethod<[Principal, Role], undefined>,
  'updateWebhookStatus' : ActorMethod<[boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];