/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Role = IDL.Variant({
  'Viewer' : IDL.Null,
  'Member' : IDL.Null,
  'Admin' : IDL.Null,
});
export const ApiKey = IDL.Text;
export const TenantId = IDL.Text;
export const ApiKeyHash = IDL.Text;
export const Time = IDL.Int;
export const Tenant = IDL.Record({
  'id' : TenantId,
  'apiKeyHash' : ApiKeyHash,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const Day = IDL.Nat;
export const Membership = IDL.Record({
  'role' : Role,
  'user' : IDL.Principal,
  'tenantId' : TenantId,
});
export const WebhookConfig = IDL.Record({
  'url' : IDL.Opt(IDL.Text),
  'signingSecret' : IDL.Text,
  'enabled' : IDL.Bool,
  'enabledEvents' : IDL.Vec(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addMemberByPrincipal' : IDL.Func([IDL.Principal, Role], [], []),
  'authenticateWithAPIKey' : IDL.Func([ApiKey], [Tenant], []),
  'configureWebhook' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Text], []),
  'getAnalyticsSummary' : IDL.Func(
      [TenantId, IDL.Nat],
      [
        IDL.Record({
          'webhookHealth' : IDL.Record({
            'failure' : IDL.Nat,
            'success' : IDL.Nat,
          }),
          'activeEndUsers' : IDL.Nat,
          'totalApiCalls' : IDL.Nat,
          'authSuccessRate' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getCurrentTenant' : IDL.Func([], [Tenant], []),
  'getDailyTrend' : IDL.Func(
      [TenantId, IDL.Nat],
      [IDL.Vec(IDL.Tuple(Day, IDL.Nat))],
      [],
    ),
  'getEventBreakdown' : IDL.Func(
      [TenantId],
      [
        IDL.Record({
          'authenticated' : IDL.Nat,
          'failed' : IDL.Nat,
          'registered' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getOrCreateTenant' : IDL.Func([], [Tenant], []),
  'getTenantMembers' : IDL.Func([], [IDL.Vec(Membership)], []),
  'getUserRole' : IDL.Func([], [Role], []),
  'getWebhookConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'url' : IDL.Opt(IDL.Text),
          'enabled' : IDL.Bool,
          'enabledEvents' : IDL.Vec(IDL.Text),
        }),
      ],
      [],
    ),
  'getWebhookDeliveries' : IDL.Func([], [IDL.Vec(WebhookConfig)], []),
  'recordAuthEvent' : IDL.Func(
      [TenantId, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'recordWebhookEvent' : IDL.Func([TenantId, IDL.Bool], [], []),
  'regenerateApiKey' : IDL.Func([], [ApiKey], []),
  'removeMember' : IDL.Func([IDL.Principal], [], []),
  'testWebhook' : IDL.Func(
      [],
      [IDL.Record({ 'status' : IDL.Nat16, 'message' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateMemberRole' : IDL.Func([IDL.Principal, Role], [], []),
  'updateWebhookStatus' : IDL.Func([IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Role = IDL.Variant({
    'Viewer' : IDL.Null,
    'Member' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const ApiKey = IDL.Text;
  const TenantId = IDL.Text;
  const ApiKeyHash = IDL.Text;
  const Time = IDL.Int;
  const Tenant = IDL.Record({
    'id' : TenantId,
    'apiKeyHash' : ApiKeyHash,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const Day = IDL.Nat;
  const Membership = IDL.Record({
    'role' : Role,
    'user' : IDL.Principal,
    'tenantId' : TenantId,
  });
  const WebhookConfig = IDL.Record({
    'url' : IDL.Opt(IDL.Text),
    'signingSecret' : IDL.Text,
    'enabled' : IDL.Bool,
    'enabledEvents' : IDL.Vec(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addMemberByPrincipal' : IDL.Func([IDL.Principal, Role], [], []),
    'authenticateWithAPIKey' : IDL.Func([ApiKey], [Tenant], []),
    'configureWebhook' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'getAnalyticsSummary' : IDL.Func(
        [TenantId, IDL.Nat],
        [
          IDL.Record({
            'webhookHealth' : IDL.Record({
              'failure' : IDL.Nat,
              'success' : IDL.Nat,
            }),
            'activeEndUsers' : IDL.Nat,
            'totalApiCalls' : IDL.Nat,
            'authSuccessRate' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getCurrentTenant' : IDL.Func([], [Tenant], []),
    'getDailyTrend' : IDL.Func(
        [TenantId, IDL.Nat],
        [IDL.Vec(IDL.Tuple(Day, IDL.Nat))],
        [],
      ),
    'getEventBreakdown' : IDL.Func(
        [TenantId],
        [
          IDL.Record({
            'authenticated' : IDL.Nat,
            'failed' : IDL.Nat,
            'registered' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getOrCreateTenant' : IDL.Func([], [Tenant], []),
    'getTenantMembers' : IDL.Func([], [IDL.Vec(Membership)], []),
    'getUserRole' : IDL.Func([], [Role], []),
    'getWebhookConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'url' : IDL.Opt(IDL.Text),
            'enabled' : IDL.Bool,
            'enabledEvents' : IDL.Vec(IDL.Text),
          }),
        ],
        [],
      ),
    'getWebhookDeliveries' : IDL.Func([], [IDL.Vec(WebhookConfig)], []),
    'recordAuthEvent' : IDL.Func(
        [TenantId, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'recordWebhookEvent' : IDL.Func([TenantId, IDL.Bool], [], []),
    'regenerateApiKey' : IDL.Func([], [ApiKey], []),
    'removeMember' : IDL.Func([IDL.Principal], [], []),
    'testWebhook' : IDL.Func(
        [],
        [IDL.Record({ 'status' : IDL.Nat16, 'message' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateMemberRole' : IDL.Func([IDL.Principal, Role], [], []),
    'updateWebhookStatus' : IDL.Func([IDL.Bool], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };