/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type TenantId = string;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface Tenant {
    id: TenantId;
    apiKeyHash: ApiKeyHash;
    owner: Principal;
    name: string;
    createdAt: Time;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface WebhookConfig {
    url?: string;
    signingSecret: string;
    enabled: boolean;
    enabledEvents: Array<string>;
}
export type Day = bigint;
export type ApiKeyHash = string;
export interface Membership {
    role: Role;
    user: Principal;
    tenantId: TenantId;
}
export type ApiKey = string;
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum Role {
    Viewer = "Viewer",
    Member = "Member",
    Admin = "Admin"
}
export interface backendInterface {
    addMemberByPrincipal(principal: Principal, role: Role): Promise<void>;
    authenticateWithAPIKey(apiKey: ApiKey): Promise<Tenant>;
    configureWebhook(url: string, enabledEvents: Array<string>): Promise<string>;
    getAnalyticsSummary(tenantId: TenantId, days: bigint): Promise<{
        webhookHealth: {
            failure: bigint;
            success: bigint;
        };
        activeEndUsers: bigint;
        totalApiCalls: bigint;
        authSuccessRate: bigint;
    }>;
    getCurrentTenant(): Promise<Tenant>;
    getDailyTrend(tenantId: TenantId, days: bigint): Promise<Array<[Day, bigint]>>;
    getEventBreakdown(tenantId: TenantId): Promise<{
        authenticated: bigint;
        failed: bigint;
        registered: bigint;
    }>;
    getOrCreateTenant(): Promise<Tenant>;
    getTenantMembers(): Promise<Array<Membership>>;
    getUserRole(): Promise<Role>;
    getWebhookConfig(): Promise<{
        url?: string;
        enabled: boolean;
        enabledEvents: Array<string>;
    }>;
    getWebhookDeliveries(): Promise<Array<WebhookConfig>>;
    recordAuthEvent(tenantId: TenantId, eventType: string, userId: string, success: boolean): Promise<void>;
    recordWebhookEvent(tenantId: TenantId, success: boolean): Promise<void>;
    regenerateApiKey(): Promise<ApiKey>;
    removeMember(userPrincipal: Principal): Promise<void>;
    testWebhook(): Promise<{
        status: number;
        message: string;
    }>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateMemberRole(userPrincipal: Principal, newRole: Role): Promise<void>;
    updateWebhookStatus(enabled: boolean): Promise<boolean>;
}
import type { Membership as _Membership, Role as _Role, TenantId as _TenantId, WebhookConfig as _WebhookConfig } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMemberByPrincipal(arg0: Principal, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMemberByPrincipal(arg0, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMemberByPrincipal(arg0, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async authenticateWithAPIKey(arg0: ApiKey): Promise<Tenant> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateWithAPIKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateWithAPIKey(arg0);
            return result;
        }
    }
    async configureWebhook(arg0: string, arg1: Array<string>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.configureWebhook(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.configureWebhook(arg0, arg1);
            return result;
        }
    }
    async getAnalyticsSummary(arg0: TenantId, arg1: bigint): Promise<{
        webhookHealth: {
            failure: bigint;
            success: bigint;
        };
        activeEndUsers: bigint;
        totalApiCalls: bigint;
        authSuccessRate: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSummary(arg0, arg1);
            return result;
        }
    }
    async getCurrentTenant(): Promise<Tenant> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTenant();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTenant();
            return result;
        }
    }
    async getDailyTrend(arg0: TenantId, arg1: bigint): Promise<Array<[Day, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTrend(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTrend(arg0, arg1);
            return result;
        }
    }
    async getEventBreakdown(arg0: TenantId): Promise<{
        authenticated: bigint;
        failed: bigint;
        registered: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventBreakdown(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventBreakdown(arg0);
            return result;
        }
    }
    async getOrCreateTenant(): Promise<Tenant> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateTenant();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateTenant();
            return result;
        }
    }
    async getTenantMembers(): Promise<Array<Membership>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTenantMembers();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTenantMembers();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(): Promise<Role> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole();
                return from_candid_Role_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole();
            return from_candid_Role_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWebhookConfig(): Promise<{
        url?: string;
        enabled: boolean;
        enabledEvents: Array<string>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebhookConfig();
                return from_candid_record_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebhookConfig();
            return from_candid_record_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWebhookDeliveries(): Promise<Array<WebhookConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebhookDeliveries();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebhookDeliveries();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordAuthEvent(arg0: TenantId, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAuthEvent(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAuthEvent(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async recordWebhookEvent(arg0: TenantId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordWebhookEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordWebhookEvent(arg0, arg1);
            return result;
        }
    }
    async regenerateApiKey(): Promise<ApiKey> {
        if (this.processError) {
            try {
                const result = await this.actor.regenerateApiKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.regenerateApiKey();
            return result;
        }
    }
    async removeMember(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMember(arg0);
            return result;
        }
    }
    async testWebhook(): Promise<{
        status: number;
        message: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.testWebhook();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.testWebhook();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateMemberRole(arg0: Principal, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberRole(arg0, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberRole(arg0, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateWebhookStatus(arg0: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWebhookStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWebhookStatus(arg0);
            return result;
        }
    }
}
function from_candid_Membership_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Membership): Membership {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_WebhookConfig_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WebhookConfig): WebhookConfig {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: [] | [string];
    signingSecret: string;
    enabled: boolean;
    enabledEvents: Array<string>;
}): {
    url?: string;
    signingSecret: string;
    enabled: boolean;
    enabledEvents: Array<string>;
} {
    return {
        url: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.url)),
        signingSecret: value.signingSecret,
        enabled: value.enabled,
        enabledEvents: value.enabledEvents
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: _Role;
    user: Principal;
    tenantId: _TenantId;
}): {
    role: Role;
    user: Principal;
    tenantId: TenantId;
} {
    return {
        role: from_candid_Role_n6(_uploadFile, _downloadFile, value.role),
        user: value.user,
        tenantId: value.tenantId
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: [] | [string];
    enabled: boolean;
    enabledEvents: Array<string>;
}): {
    url?: string;
    enabled: boolean;
    enabledEvents: Array<string>;
} {
    return {
        url: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.url)),
        enabled: value.enabled,
        enabledEvents: value.enabledEvents
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Viewer: null;
} | {
    Member: null;
} | {
    Admin: null;
}): Role {
    return "Viewer" in value ? Role.Viewer : "Member" in value ? Role.Member : "Admin" in value ? Role.Admin : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WebhookConfig>): Array<WebhookConfig> {
    return value.map((x)=>from_candid_WebhookConfig_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Membership>): Array<Membership> {
    return value.map((x)=>from_candid_Membership_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Role_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    Viewer: null;
} | {
    Member: null;
} | {
    Admin: null;
} {
    return value == Role.Viewer ? {
        Viewer: null
    } : value == Role.Member ? {
        Member: null
    } : value == Role.Admin ? {
        Admin: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
